/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GalleryItem = IDL.Record({ 'caption' : IDL.Text });
export const ProductCategory = IDL.Record({
  'name' : IDL.Text,
  'exampleItems' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
});
export const Review = IDL.Record({
  'date' : IDL.Text,
  'reviewText' : IDL.Text,
  'reviewerName' : IDL.Text,
  'rating' : IDL.Nat8,
});
export const ShopInfo = IDL.Record({
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'timings' : IDL.Text,
});

export const idlService = IDL.Service({
  'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getProductCategories' : IDL.Func([], [IDL.Vec(ProductCategory)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getShopInfo' : IDL.Func([], [ShopInfo], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GalleryItem = IDL.Record({ 'caption' : IDL.Text });
  const ProductCategory = IDL.Record({
    'name' : IDL.Text,
    'exampleItems' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
  });
  const Review = IDL.Record({
    'date' : IDL.Text,
    'reviewText' : IDL.Text,
    'reviewerName' : IDL.Text,
    'rating' : IDL.Nat8,
  });
  const ShopInfo = IDL.Record({
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'timings' : IDL.Text,
  });
  
  return IDL.Service({
    'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getProductCategories' : IDL.Func(
        [],
        [IDL.Vec(ProductCategory)],
        ['query'],
      ),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getShopInfo' : IDL.Func([], [ShopInfo], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };