/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GalleryItem { 'caption' : string }
export interface ProductCategory {
  'name' : string,
  'exampleItems' : Array<string>,
  'description' : string,
}
export interface Review {
  'date' : string,
  'reviewText' : string,
  'reviewerName' : string,
  'rating' : number,
}
export interface ShopInfo {
  'tagline' : string,
  'name' : string,
  'whatsapp' : string,
  'address' : string,
  'phone' : string,
  'timings' : string,
}
export interface _SERVICE {
  'getGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getProductCategories' : ActorMethod<[], Array<ProductCategory>>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'getShopInfo' : ActorMethod<[], ShopInfo>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];